import type { CheckupItem } from './types';

export const checkupItems: CheckupItem[] = [
  {
    id: 'ck-001',
    category: 'passwords',
    title: 'Password Strength',
    description: 'Check if your passwords are strong and unique for each account.',
    status: 'action_needed',
    recommendation: 'Use a password manager to generate and store strong, unique passwords for each account. Avoid using personal information in passwords.',
    severity: 'high',
    icon: '🔑',
  },
  {
    id: 'ck-002',
    category: 'accounts',
    title: 'Account Security',
    description: 'Review your online accounts for suspicious activity.',
    status: 'at_risk',
    recommendation: 'Check recent login activity on your Google, Facebook, and email accounts. Remove unrecognized devices.',
    severity: 'high',
    icon: '👤',
  },
  {
    id: 'ck-003',
    category: '2fa',
    title: 'Two-Factor Authentication',
    description: 'Enable 2FA on all important accounts for extra security.',
    status: 'action_needed',
    recommendation: 'Enable 2FA on email, banking, social media, and payment apps using authenticator app, not SMS.',
    severity: 'high',
    icon: '🔐',
  },
  {
    id: 'ck-004',
    category: 'email_exposure',
    title: 'Email Exposure Check',
    description: 'Check if your email has been involved in any data breaches.',
    status: 'action_needed',
    recommendation: 'Check haveibeenpwned.com for your email. Change passwords for any compromised accounts immediately.',
    severity: 'medium',
    icon: '📧',
  },
  {
    id: 'ck-005',
    category: 'phone_exposure',
    title: 'Phone Number Exposure',
    description: 'Check if your phone number is exposed online.',
    status: 'unknown',
    recommendation: 'Avoid posting your phone number publicly on social media. Use privacy settings to limit visibility.',
    severity: 'medium',
    icon: '📱',
  },
  {
    id: 'ck-006',
    category: 'app_permissions',
    title: 'App Permissions Audit',
    description: 'Review which apps have access to your camera, mic, contacts, and location.',
    status: 'at_risk',
    recommendation: 'Revoke unnecessary permissions. Remove apps you no longer use. Check permissions in phone settings.',
    severity: 'medium',
    icon: '⚙️',
  },
  {
    id: 'ck-007',
    category: 'social_media',
    title: 'Social Media Privacy',
    description: 'Audit your social media privacy settings and public information.',
    status: 'action_needed',
    recommendation: 'Set profiles to private. Remove personal info like phone, address, and birthday from public view.',
    severity: 'medium',
    icon: '🌐',
  },
  {
    id: 'ck-008',
    category: 'financial_safety',
    title: 'Financial Safety Check',
    description: 'Review banking and UPI app security settings.',
    status: 'secure',
    recommendation: 'Keep UPI PIN private. Enable transaction alerts. Check beneficiary list in net banking.',
    severity: 'high',
    icon: '💰',
  },
];

export function getCheckupSummary(): { secure: number; atRisk: number; actionNeeded: number; unknown: number } {
  return {
    secure: checkupItems.filter((i) => i.status === 'secure').length,
    atRisk: checkupItems.filter((i) => i.status === 'at_risk').length,
    actionNeeded: checkupItems.filter((i) => i.status === 'action_needed').length,
    unknown: checkupItems.filter((i) => i.status === 'unknown').length,
  };
}
