import type { LearnFraudType } from './types';

export const fraudTypes: LearnFraudType[] = [
  {
    id: 'otp-fraud',
    title: 'OTP Fraud',
    icon: '🔐',
    howItWorks: 'Fraudster calls or messages pretending to be from bank, asking for OTP "to verify" something. They create urgency — "Your account will be blocked!" Once you share OTP, they drain your account.',
    realExample: 'Message: "Your SBI account will be suspended. Call 1800-xxx-xxx immediately. Your OTP is 789456. Share to verify." This is 100% fake.',
    redFlags: [
      'Someone asking for OTP',
      'Threatening to block account',
      'Urgent tone with deadline',
      'Fake customer care numbers',
    ],
    protectionSteps: [
      'Never share OTP with anyone — ever.',
      'Bank never asks OTP on call or message.',
      'Hang up and call official bank number.',
      'Report number on Chakshu portal.',
    ],
    quiz: {
      question: 'Bank employee calls asking for OTP to "verify" your account. What should you do?',
      options: [
        'Share OTP to keep account safe',
        'Ask for their employee ID and share OTP',
        'Hang up — bank never asks OTP',
        'Call them back later',
      ],
      correctIndex: 2,
      explanation: '✅ Sahi jawab! Banks kabhi bhi OTP nahi maangte. Aise calls turant cut karo aur bank ke official number par call karo.',
    },
  },
  {
    id: 'kyc-scam',
    title: 'KYC Scam',
    icon: '📋',
    howItWorks: 'You get a message: "Your KYC is expired. Click link to update." The link opens a fake website that looks exactly like your bank. You enter details — and scammers steal everything.',
    realExample: 'SMS: "Axis Bank: Your KYC has expired. Update now: axis-kyc[.]com or account will be blocked." Fake website looks identical to Axis Bank.',
    redFlags: [
      'KYC expiry message from unknown number',
      'Link with misspelled bank name',
      'Threat of account blocking',
      'Asking for sensitive information',
    ],
    protectionSteps: [
      'Don\'t click links in KYC messages.',
      'KYC doesn\'t expire via SMS link.',
      'Update KYC only in bank app or branch.',
      'Report fake SMS on cybercrime portal.',
    ],
    quiz: {
      question: 'You got SMS: "Your HDFC KYC expired. Click: hdfc-verify[.]com" What to do?',
      options: [
        'Click link and update KYC',
        'Ignore — bank never sends KYC links in SMS',
        'Forward to friends for advice',
        'Call the number in SMS',
      ],
      correctIndex: 1,
      explanation: '✅ Bilkul sahi! Banks SMS mein KYC update ke liye link nahi bhejte. Hamesha official app ya branch mein jao.',
    },
  },
  {
    id: 'qr-scam',
    title: 'QR Scam',
    icon: '📸',
    howItWorks: 'Fraudster sends a QR code saying "Scan this to get money" or "Scan to pay." But scanning their QR code triggers a payment FROM your account, not TO you. QR is for receiving, not for sending.',
    realExample: 'You want to sell something on OLX. "Buyer" says: "Scan my QR code to get payment." You scan and ₹5000 is debited. This is reverse QR scam.',
    redFlags: [
      'Someone sending QR code for payment',
      'Asking to scan QR to receive money',
      'Urging to scan quickly',
      'QR code on random websites',
    ],
    protectionSteps: [
      'QR code is for receiving money, not sending.',
      'Don\'t scan QR codes from unknown people.',
      'In UPI, you scan to pay, not to receive.',
      'Use "Request Money" feature for receiving.',
    ],
    quiz: {
      question: 'A "buyer" says: "Scan my QR code to get payment for your item." What should you do?',
      options: [
        'Scan the QR code',
        'Ask them to send money via UPI number',
        'It\'s a scam — block them',
        'Scan after checking balance',
      ],
      correctIndex: 2,
      explanation: '✅ Correct! QR scan se payment hoti hai, receive nahi. Ye reverse QR scam hai. Aise logon ko block karo.',
    },
  },
  {
    id: 'job-scam',
    title: 'Job Scam',
    icon: '💼',
    howItWorks: 'Fake job offers on WhatsApp/Telegram. "Work from home, earn ₹50,000/month!" They ask for "registration fee," "training fee," or "security deposit." After payment — they disappear.',
    realExample: 'WhatsApp: "Urgent hiring! Part time job. 2 hours daily. ₹30,000/month. Contact for registration. Fee: ₹999." This is 100% scam.',
    redFlags: [
      'Too good salary for simple work',
      'Asking money for registration',
      'No interview or proper process',
      'Telegram/WhatsApp groups',
    ],
    protectionSteps: [
      'Real jobs never ask money.',
      'Research company on Google.',
      'Check on LinkedIn for company page.',
      'Report fake job offers on cyber portal.',
    ],
    quiz: {
      question: 'Job offer says: "Pay ₹2000 for training, then earn ₹1 lakh/month." What to do?',
      options: [
        'Pay and get rich',
        'Ask for bank details before paying',
        'It\'s a scam — real jobs don\'t charge',
        'Negotiate for lower fee',
      ],
      correctIndex: 2,
      explanation: '✅ Shandaar! Jobs ke liye paise nahi lete. Company aapko skill ke liye pay karti hai, aap company ko nahi.',
    },
  },
  {
    id: 'delivery-scam',
    title: 'Delivery Scam',
    icon: '📦',
    howItWorks: 'SMS: "Your package is stuck. Pay ₹30 customs fee to this link." You pay ₹30 — they get your card details. Later, they drain your account. Same with "update address" links.',
    realExample: 'SMS: "India Post: Your parcel with tracking ID is held. Pay ₹25 customs fee: indi-post[.]com" India Post doesn\'t send such SMS.',
    redFlags: [
      'Delivery SMS from unknown number',
      'Asking to pay small fee',
      'Link with fake courier name',
      'No tracking ID you recognize',
    ],
    protectionSteps: [
      'Check orders on official app/website.',
      'Don\'t click delivery SMS links.',
      'Real courier companies don\'t ask fee via SMS.',
      'Use official tracking on courier website.',
    ],
    quiz: {
      question: 'SMS says: "FedEx: Your package held. Pay ₹25 customs: fedex-deliver[.]in" What next?',
      options: [
        'Pay ₹25 — it\'s small amount',
        'Click to track your package',
        'Ignore — you\'re not expecting any package',
        'Forward to family',
      ],
      correctIndex: 2,
      explanation: '✅ Sahi! Jab aapne kuch order nahi kiya toh package ka sawaal hi nahi. Ye delivery scam hai, turant delete karo.',
    },
  },
  {
    id: 'investment-scam',
    title: 'Investment Scam',
    icon: '📈',
    howItWorks: 'Scammers promise "doubled money in 3 days," "guaranteed 10% monthly returns." They show fake profit screenshots. Initial small returns build trust. Then you invest big — and they vanish.',
    realExample: 'WhatsApp group: "I made ₹2 lakh in 1 week! Join my investment club." Everything is fake. Screenshots are edited. Group has 50 fake members and 1 real victim.',
    redFlags: [
      'Guaranteed high returns',
      'Fake profit screenshots',
      'Pressure to invest quickly',
      'No SEBI registration',
      'Referral bonus for bringing friends',
    ],
    protectionSteps: [
      'No legitimate investment guarantees returns.',
      'Check SEBI registration at sebi.gov.in.',
      'Don\'t invest based on WhatsApp groups.',
      'Consult SEBI registered advisor only.',
    ],
    quiz: {
      question: 'Someone promises "100% return in 1 week." What is this?',
      options: [
        'Great investment opportunity',
        '100% risk of losing money',
        'Legal if they have website',
        'Good if friends also invested',
      ],
      correctIndex: 1,
      explanation: '✅ Exactly! Agar koi 1 hafte mein double money ka promise kar raha hai, toh woh 100% scam hai. Investment mein guaranteed returns nahi hote.',
    },
  },
];
